const MessageType = {
    BROADCAST: 'BROADCAST',
    QUERY_LATEST: 'QUERY_LATEST',
    QUERY_ALL: 'QUERY_ALL',
    RESPONSE_BLOCKCHAIN: 'RESPONSE_BLOCKCHAIN',
    NODE_ADDRESSES: 'NODE_ADDRESSES',
    BLOCK_PROPOSAL: 'BLOCK_PROPOSAL',
    BLOCK_VOTE: 'BLOCK_VOTE',
    NEW_TRANSACTION: 'NEW_TRANSACTION',
    CURRENT_HEIGHT: 'CURRENT_HEIGHT'
};

module.exports = {
    MessageType
};
